[theme]
primaryColor="#3b80cfff"
backgroundColor="#2a2a2a"
secondaryBackgroundColor="#121212"
textColor="#ffffff"
linkColor="#3b80cfff"
borderColor = "#7c7c7c"
showWidgetBorder = true
font="sans serif"